apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-for-k8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-k8
  template:
    metadata:
      labels:
        app: node-app-k8
    spec:
      containers:
      - name: node-app-k8
        image: kshitijg/node-app-k8:3
        # env:
        #   - name: MONGO_HOST
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mongo-config
        #         key: MONGO_HOST
        #   - name: MONGO_PORT
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mongo-config
        #         key: MONGO_PORT


---

# apiVersion: v1
# kind: Service
# metadata:
#   name: service-node-app
# spec:
#   ports:
#     - name: http
#       port: 8080
#       targetPort: 3000
#   selector:
#     app: node-app
#   type: LoadBalancer


